name = "Finance-Robinhood"
badges=['travis', 'metacpan', 'appveyor']
module_maker="ModuleBuildTiny"
license="artistic_2"
authority="cpan:SANKO"

[release]
hook=[
    'perltidy `git ls-tree -r HEAD --name-only | grep -E "(lib|t|eg)/.+\.(pm|pl|t)$"`'
]
